GROQ_KEY = "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"
GEMINI_KEY = "AQ.Ab8RN6JYTHJVARZjW67W4oZbV2UId3BSCvU2HGl4IJOVQxPnQ"
TELEGRAM_BOT_TOKEN = "8794257218:AAGYGDqPUEJdI3UahL07Pe86IgcLCfIn20g"
TELEGRAM_CHAT_ID = "8600332637"
